// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/proto/tasks.proto

package tasksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task is the unit of work handed from mastermind to a worker.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier assigned by mastermind. Matches the `id` column of the
	// mastermind tasks table (UUID v4 serialized canonical 8-4-4-4-12).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Logical task type. Workers dispatch on this string to decide which
	// handler to run.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Opaque, caller-defined JSON payload. Mastermind stores this verbatim and
	// does not interpret it.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_internal_proto_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ClaimTaskRequest asks mastermind for the next available task.
type ClaimTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier for the calling worker, typically "<hostname>-<pid>" or
	// a UUID chosen at process start. Mastermind records this on the claim for
	// debugging and poison-pill attribution.
	WorkerId      string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRequest) Reset() {
	*x = ClaimTaskRequest{}
	mi := &file_internal_proto_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRequest) ProtoMessage() {}

func (x *ClaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ClaimTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// ClaimTaskResponse carries a claimed task. On empty-queue the server returns
// NOT_FOUND instead of an empty response, so `task` is guaranteed non-nil on
// success.
type ClaimTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskResponse) Reset() {
	*x = ClaimTaskResponse{}
	mi := &file_internal_proto_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskResponse) ProtoMessage() {}

func (x *ClaimTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskResponse.ProtoReflect.Descriptor instead.
func (*ClaimTaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *ClaimTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// HeartbeatRequest refreshes the caller's lease on an owned task.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{4}
}

// ReportResultRequest finalizes a task with either success or failure.
// `outcome` is a oneof so that "neither set" and "both set" are unrepresentable
// on the wire.
type ReportResultRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId   string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ReportResultRequest_Success_
	//	*ReportResultRequest_Failure_
	Outcome       isReportResultRequest_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_internal_proto_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetOutcome() isReportResultRequest_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ReportResultRequest) GetSuccess() *ReportResultRequest_Success {
	if x != nil {
		if x, ok := x.Outcome.(*ReportResultRequest_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ReportResultRequest) GetFailure() *ReportResultRequest_Failure {
	if x != nil {
		if x, ok := x.Outcome.(*ReportResultRequest_Failure_); ok {
			return x.Failure
		}
	}
	return nil
}

type isReportResultRequest_Outcome interface {
	isReportResultRequest_Outcome()
}

type ReportResultRequest_Success_ struct {
	Success *ReportResultRequest_Success `protobuf:"bytes,3,opt,name=success,proto3,oneof"`
}

type ReportResultRequest_Failure_ struct {
	Failure *ReportResultRequest_Failure `protobuf:"bytes,4,opt,name=failure,proto3,oneof"`
}

func (*ReportResultRequest_Success_) isReportResultRequest_Outcome() {}

func (*ReportResultRequest_Failure_) isReportResultRequest_Outcome() {}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_internal_proto_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{6}
}

// Success signals the task completed. Empty today, but kept as a message
// (not a bare flag) so fields like output summary or timing can be added
// without a breaking change.
type ReportResultRequest_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest_Success) Reset() {
	*x = ReportResultRequest_Success{}
	mi := &file_internal_proto_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest_Success) ProtoMessage() {}

func (x *ReportResultRequest_Success) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest_Success.ProtoReflect.Descriptor instead.
func (*ReportResultRequest_Success) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{5, 0}
}

// Failure signals the task did not complete. `message` is surfaced as
// `last_error` in the mastermind tasks table and included in retry
// bookkeeping.
type ReportResultRequest_Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest_Failure) Reset() {
	*x = ReportResultRequest_Failure{}
	mi := &file_internal_proto_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest_Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest_Failure) ProtoMessage() {}

func (x *ReportResultRequest_Failure) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest_Failure.ProtoReflect.Descriptor instead.
func (*ReportResultRequest_Failure) Descriptor() ([]byte, []int) {
	return file_internal_proto_tasks_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ReportResultRequest_Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_proto_tasks_proto protoreflect.FileDescriptor

const file_internal_proto_tasks_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/tasks.proto\x12\x10elpulpo.tasks.v1\"D\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"/\n" +
	"\x10ClaimTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"?\n" +
	"\x11ClaimTaskResponse\x12*\n" +
	"\x04task\x18\x01 \x01(\v2\x16.elpulpo.tasks.v1.TaskR\x04task\"H\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"\x13\n" +
	"\x11HeartbeatResponse\"\x9c\x02\n" +
	"\x13ReportResultRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12I\n" +
	"\asuccess\x18\x03 \x01(\v2-.elpulpo.tasks.v1.ReportResultRequest.SuccessH\x00R\asuccess\x12I\n" +
	"\afailure\x18\x04 \x01(\v2-.elpulpo.tasks.v1.ReportResultRequest.FailureH\x00R\afailure\x1a\t\n" +
	"\aSuccess\x1a#\n" +
	"\aFailure\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\t\n" +
	"\aoutcome\"\x16\n" +
	"\x14ReportResultResponse2\x98\x02\n" +
	"\vTaskService\x12T\n" +
	"\tClaimTask\x12\".elpulpo.tasks.v1.ClaimTaskRequest\x1a#.elpulpo.tasks.v1.ClaimTaskResponse\x12T\n" +
	"\tHeartbeat\x12\".elpulpo.tasks.v1.HeartbeatRequest\x1a#.elpulpo.tasks.v1.HeartbeatResponse\x12]\n" +
	"\fReportResult\x12%.elpulpo.tasks.v1.ReportResultRequest\x1a&.elpulpo.tasks.v1.ReportResultResponseB8Z6github.com/sbogutyn/el-pulpo-ai/internal/proto;tasksv1b\x06proto3"

var (
	file_internal_proto_tasks_proto_rawDescOnce sync.Once
	file_internal_proto_tasks_proto_rawDescData []byte
)

func file_internal_proto_tasks_proto_rawDescGZIP() []byte {
	file_internal_proto_tasks_proto_rawDescOnce.Do(func() {
		file_internal_proto_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_tasks_proto_rawDesc), len(file_internal_proto_tasks_proto_rawDesc)))
	})
	return file_internal_proto_tasks_proto_rawDescData
}

var file_internal_proto_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_proto_tasks_proto_goTypes = []any{
	(*Task)(nil),                        // 0: elpulpo.tasks.v1.Task
	(*ClaimTaskRequest)(nil),            // 1: elpulpo.tasks.v1.ClaimTaskRequest
	(*ClaimTaskResponse)(nil),           // 2: elpulpo.tasks.v1.ClaimTaskResponse
	(*HeartbeatRequest)(nil),            // 3: elpulpo.tasks.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 4: elpulpo.tasks.v1.HeartbeatResponse
	(*ReportResultRequest)(nil),         // 5: elpulpo.tasks.v1.ReportResultRequest
	(*ReportResultResponse)(nil),        // 6: elpulpo.tasks.v1.ReportResultResponse
	(*ReportResultRequest_Success)(nil), // 7: elpulpo.tasks.v1.ReportResultRequest.Success
	(*ReportResultRequest_Failure)(nil), // 8: elpulpo.tasks.v1.ReportResultRequest.Failure
}
var file_internal_proto_tasks_proto_depIdxs = []int32{
	0, // 0: elpulpo.tasks.v1.ClaimTaskResponse.task:type_name -> elpulpo.tasks.v1.Task
	7, // 1: elpulpo.tasks.v1.ReportResultRequest.success:type_name -> elpulpo.tasks.v1.ReportResultRequest.Success
	8, // 2: elpulpo.tasks.v1.ReportResultRequest.failure:type_name -> elpulpo.tasks.v1.ReportResultRequest.Failure
	1, // 3: elpulpo.tasks.v1.TaskService.ClaimTask:input_type -> elpulpo.tasks.v1.ClaimTaskRequest
	3, // 4: elpulpo.tasks.v1.TaskService.Heartbeat:input_type -> elpulpo.tasks.v1.HeartbeatRequest
	5, // 5: elpulpo.tasks.v1.TaskService.ReportResult:input_type -> elpulpo.tasks.v1.ReportResultRequest
	2, // 6: elpulpo.tasks.v1.TaskService.ClaimTask:output_type -> elpulpo.tasks.v1.ClaimTaskResponse
	4, // 7: elpulpo.tasks.v1.TaskService.Heartbeat:output_type -> elpulpo.tasks.v1.HeartbeatResponse
	6, // 8: elpulpo.tasks.v1.TaskService.ReportResult:output_type -> elpulpo.tasks.v1.ReportResultResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_tasks_proto_init() }
func file_internal_proto_tasks_proto_init() {
	if File_internal_proto_tasks_proto != nil {
		return
	}
	file_internal_proto_tasks_proto_msgTypes[5].OneofWrappers = []any{
		(*ReportResultRequest_Success_)(nil),
		(*ReportResultRequest_Failure_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_tasks_proto_rawDesc), len(file_internal_proto_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_tasks_proto_goTypes,
		DependencyIndexes: file_internal_proto_tasks_proto_depIdxs,
		MessageInfos:      file_internal_proto_tasks_proto_msgTypes,
	}.Build()
	File_internal_proto_tasks_proto = out.File
	file_internal_proto_tasks_proto_goTypes = nil
	file_internal_proto_tasks_proto_depIdxs = nil
}
